merodokan2-master/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name="register"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),

    path('dashboard', views.Dashboard.as_view(), name="dashboard"),
    path('update/profile', views.UpdateProfile.as_view(), name="update_profile"),
    path('chanage-password/', views.ChangePassword.as_view(),
         name="change_password"),
    path('my-product/', views.MyProduct.as_view(),
         name="my_products"),


    path('logout/', views.LogoutView.as_view(), name='logout'),




]

merodokan2-master/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace="accounts")),

    path('', include('products.urls', namespace="products")),

    path('pages/', include('pages.urls', namespace="pages")),



    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.FORCE_STATIC_FILE_SERVING and not settings.DEBUG:
    settings.DEBUG = True
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    settings.DEBUG = False

merodokan2-master/pages/urls.py
from django.urls import path
from . import views

app_name = "pages"

urlpatterns = [
    path('how-it-works/', views.HowItWorks.as_view(), name='how_it_works'),
    path('faq/', views.Faq.as_view(), name='faq'),
    path('feedback/', views.FeedBack.as_view(), name='feedback'),
    path('contact/', views.Contact.as_view(), name='contact'),
    path('terms/', views.Terms.as_view(), name='terms'),
    path('terms/', views.Terms.as_view(), name='terms'),
    path('privacy/', views.Privacy.as_view(), name='privacy'),
]

merodokan2-master/products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path('', views.AdList.as_view(), name='home'),
    path('detail/<slug:slug>/', views.AdDetail.as_view(), name="ad_detail"),

    path('post-ad/', views.PostAd.as_view(), name='post_ad'),
    path('delete-ad/<int:id>', views.DeleteAdd.as_view(), name='delete_ad'),

    path('user/product/<str:username>/',
         views.UserProduct.as_view(), name="user_product"),

    path('category/product/<str:slug>/',
         views.CategoryProduct.as_view(), name="category_product"),

    path('update/product/<slug:slug>/',
         views.UpdateProduct.as_view(), name="update_product"),


    path('product/search/',
         views.SearchProduct.as_view(), name="search_product"),

    path('ads/<int:year>/<int:month>/', views.ProductMonthArchiveView.as_view(month_format='%m'),
         name="archive_month_ads"),
     path('favourites/', views.product_favourite_list, name='product_favourite_list'),
     path('addfavourites/<int:id>', views.favourites, name='addfavourite'),

]

merodokan2-master/templates/partials/_alert.html
{% if messages %}
{% for message in messages %}

    <div class="alert alert-{{ message.tags }} alert-dismissable text-center" role="alert">
        <button type="button" data-dismiss="alert" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            Error:
            {% else %}
            {{ message.tags|title }}:
            {% endif %}
        </strong>
        {{ message }}
    </div>

{% endfor %}
{% endif %}

merodokan2-master/templates/partials/_categories.html
<div class="categories">
                <div class="container">
                    {% for cat in all_categories %}


                    <div class="col-md-2 focus-grid">
                        <a href="{% url 'products:category_product' cat.slug %}">
                            <div class="focus-border">
                                <div class="focus-layout">
                                    <div class="focus-image">
                                        <img src="{{cat.image.url}}" height="98px" alt="">
                                    </div>
                                    <h4 class="clrchg">{{cat.name}}</h4>
                                </div>
                            </div>
                        </a>
                    </div>

                    {% endfor %}

                    <div class="clearfix"></div>
                </div>
            </div>

merodokan2-master/templates/partials/_css.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-select.css' %}">
<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
<link rel="stylesheet" href="{% static 'css/flexslider.css' %}" type="text/css" media="screen" />
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui1.css' %}">
<link href="{% static 'css/jquery.uls.css' %}" rel="stylesheet"/>
<link href="{% static 'css/jquery.uls.grid.css' %}" rel="stylesheet"/>
<link href="{% static 'css/jquery.uls.lcd.css' %}" rel="stylesheet"/>
<link href="{% static 'css/jquery-confirm.css' %}" rel="stylesheet"/>

merodokan2-master/templates/partials/_footer.html
<!-- Footer -->
<footer class="page-footer font-small special-color-dark pt-4">

    <!-- Footer Elements -->
    <div class="container">
  
      <!-- Social buttons -->
      <ul class="list-unstyled list-inline text-center">
        <li class="list-inline-item">
          <a class="btn-floating btn-fb mx-1">
            <i class="fab fa-facebook-f"> </i>
          </a>
        </li>
        <li class="list-inline-item">
          <a class="btn-floating btn-tw mx-1">
            <i class="fab fa-twitter"> </i>
          </a>
        </li>
        <li class="list-inline-item">
          <a class="btn-floating btn-gplus mx-1">
            <i class="fab fa-google-plus-g"> </i>
          </a>
        </li>
        <li class="list-inline-item">
          <a class="btn-floating btn-li mx-1">
            <i class="fab fa-linkedin-in"> </i>
          </a>
        </li>
        <li class="list-inline-item">
          <a class="btn-floating btn-dribbble mx-1">
            <i class="fab fa-dribbble"> </i>
          </a>
        </li>
      </ul>
      <!-- Social buttons -->
  
    </div>
    <!-- Footer Elements -->
  
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2020 Copyright:
      <a href="https://mdbootstrap.com/"> MeroDokan</a>
    </div>
    <!-- Copyright -->
  
  </footer>
  <!-- Footer -->

merodokan2-master/templates/partials/_header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'products:home' %}">MeroDokan</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'products:home' %}">Home
                
            </a>
          </li>

          


        </ul>
        <ul class="nav  navbar-right px-3">
          <a class="nav-link active" aria-current="page" href="{% url 'products:home' %}" style="margin-right:5px;">
        
        </a>
        <a  class="btn btn-success" href="{% url 'products:post_ad' %}">Sell</a> 
          {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle btn-info btn-info " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              My Account
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'accounts:my_products' %}">My Proudcts</a>
              <a class="dropdown-item" href="{% url 'accounts:change_password' %}">Change Password</a>

          </li>
         
          <a  class="btn btn-warning" href="{% url 'accounts:logout' %}">Logout</a>
      {% else %}
      
          <a  class="btn btn-dark" href="{% url 'accounts:login' %}" style="margin-right:5px">Login</a>
          <a  class="btn btn-info" href="{% url 'accounts:register' %}">Register</a>
      {% endif %}

        </ul>

      </div>
    </div>
  </nav>
  

merodokan2-master/templates/partials/_js.html
{% load static %}

<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/bootstrap-select.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.leanModal.min.js' %}"></script>
<script src="{% static 'js/jquery.uls.data.js' %}"></script>
<script src="{% static 'js/jquery.uls.data.utils.js' %}"></script>
<script src="{% static 'js/jquery.uls.lcd.js' %}"></script>
<script src="{% static 'js/jquery.uls.languagefilter.js' %}"></script>
<script src="{% static 'js/jquery.uls.regionfilter.js' %}"></script>
<script src="{% static 'js/jquery.uls.core.js' %}"></script>
<script src="{% static 'js/jquery-confirm.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

merodokan2-master/templates/partials/_pagination.html
 <ul class="pagination pagination-sm">
                    {% if page_obj.has_previous %}
                        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                        <li><a href="javascript:void(0)" class="disabled">&laquo;</a></li>
                    {% endif %}

                    {% for i in page_obj.paginator.page_range %}
                        {% if page_obj.number == i %}
                            <li><a href="?page={{ i }}">{{i}}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                    {% else %}
                        <li><a href="javascript:void(0)" class="disabled">&raquo;</a></li>
                    {% endif %}

                </ul>

merodokan2-master/templates/partials/_search.html
<div class="container">
    <div class="select-box" style="margin-right: -31px;">

        <form action="{% url 'products:search_product' %}" method="GET">
            <div class="select-city-for-local-ads ads-list" style="width: 232px;">
                <label>Select your city to see local ads</label>
                    <select class="selectpicker show-tick" data-live-search="true" name="city">


                           {% for city in all_city %}
                                <option value="{{city}}">{{city}}</option>
                            {% endfor %}




                    </select>
            </div>

            <div class="select-city-for-local-ads ads-list">
                <label>Select your city to see local ads</label>
                    <select class="selectpicker show-tick" data-live-search="true" name="area">

                            {% for area in all_area %}
                                <option value="{{area}}">{{area}}</option>
                            {% endfor %}





                    </select>
            </div>
            <div class="browse-category ads-list" >
                <label>Browse Categories</label>
                <select class="selectpicker show-tick" data-live-search="true" name="category">
                    {% for cat in all_categories %}
                        <option data-tokens="{{cat.name}}" value="{{cat.id}}">{{cat.name}}</option>
                    {% endfor %}

                </select>
            </div>
            <div class="search-product ads-list">
                <label>Search for a specific product</label>
                <div class="search">
                    <div id="custom-search-input">
                    <div class="input-group">
                        <input name="search" type="text" class="form-control input-lg" placeholder="Search Product" />
                        <span class="input-group-btn">
                            <button class="btn btn-info btn-lg" type="submit">
                                <i class="glyphicon glyphicon-search"></i>
                            </button>
                        </span>
                    </div>
                </div>
                </div>
            </div>
        </form>

        <div class="clearfix"></div>
    </div>
</div>