merodokan2-master/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name="register"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),

    path('dashboard', views.Dashboard.as_view(), name="dashboard"),
    path('update/profile', views.UpdateProfile.as_view(), name="update_profile"),
    path('chanage-password/', views.ChangePassword.as_view(),
         name="change_password"),
    path('my-product/', views.MyProduct.as_view(),
         name="my_products"),


    path('logout/', views.LogoutView.as_view(), name='logout'),




]

merodokan2-master/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace="accounts")),

    path('', include('products.urls', namespace="products")),

    path('pages/', include('pages.urls', namespace="pages")),



    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.FORCE_STATIC_FILE_SERVING and not settings.DEBUG:
    settings.DEBUG = True
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    settings.DEBUG = False

merodokan2-master/pages/urls.py
from django.urls import path
from . import views

app_name = "pages"

urlpatterns = [
    path('how-it-works/', views.HowItWorks.as_view(), name='how_it_works'),
    path('faq/', views.Faq.as_view(), name='faq'),
    path('feedback/', views.FeedBack.as_view(), name='feedback'),
    path('contact/', views.Contact.as_view(), name='contact'),
    path('terms/', views.Terms.as_view(), name='terms'),
    path('terms/', views.Terms.as_view(), name='terms'),
    path('privacy/', views.Privacy.as_view(), name='privacy'),
]

merodokan2-master/products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path('', views.AdList.as_view(), name='home'),
    path('detail/<slug:slug>/', views.AdDetail.as_view(), name="ad_detail"),

    path('post-ad/', views.PostAd.as_view(), name='post_ad'),
    path('delete-ad/<int:id>', views.DeleteAdd.as_view(), name='delete_ad'),

    path('user/product/<str:username>/',
         views.UserProduct.as_view(), name="user_product"),

    path('category/product/<str:slug>/',
         views.CategoryProduct.as_view(), name="category_product"),

    path('update/product/<slug:slug>/',
         views.UpdateProduct.as_view(), name="update_product"),


    path('product/search/',
         views.SearchProduct.as_view(), name="search_product"),

    path('ads/<int:year>/<int:month>/', views.ProductMonthArchiveView.as_view(month_format='%m'),
         name="archive_month_ads"),
     path('favourites/', views.product_favourite_list, name='product_favourite_list'),
     path('addfavourites/<int:id>', views.favourites, name='addfavourite'),

]

merodokan2-master/accounts/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.contrib.auth.models import User


# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='user_profile')
    profile_pic = models.ImageField(
        upload_to="profile/%Y/%m/%d/", default="profile/default.png")
    phone_number = models.CharField(max_length=15, default='01xxxxxxxxxx')
    city = models.CharField(default='Your city', max_length=255)
    email_confirmed = models.BooleanField(default=False)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    try:
        if created:
            Profile.objects.create(user=instance)
        else:
            instance.user_profile.save()
    except Exception as e:
        pass

merodokan2-master/accounts/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    phone_number = forms.CharField()
    city = forms.CharField()

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'phone_number',
                  'city', 'password1', 'password2', )

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

        self.fields['email'].required = True
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['phone_number'].required = True
        self.fields['city'].required = True


class LoginForm(forms.Form):
    username = forms.CharField(label='Your username', required=True)
    password = forms.CharField(widget=forms.PasswordInput())


class UpdateProfileForm(ModelForm):
    phone_number = forms.CharField()
    city = forms.CharField()

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'phone_number', 'city',)

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        user = self.request.user
        super(UpdateProfileForm, self).__init__(*args, **kwargs)

        self.fields['phone_number'].initial = user.user_profile.phone_number
        self.fields['first_name'].initial = user.first_name
        self.fields['last_name'].initial = user.last_name
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        # self.fields['bio'].initial = user.user_profile.bio
        self.fields['city'].initial = user.user_profile.city

merodokan2-master/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from accounts.tokens import account_activation_token
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from products.models import Product, Category
from django.contrib.auth.models import User
from .forms import SignUpForm, LoginForm, UpdateProfileForm
from .mixins import AictiveUserRequiredMixin
from django.views import View, generic

# Create your views here.


class RegisterView(View):
    def get(self, request, *args, **kwrags):
        signup_form = SignUpForm()
        context = {
            'signup_form': signup_form,
            'title': 'Register'
        }
        return render(request, 'accounts/register.html', context)

    def post(self, request, *args, **kwrags):
        signup_form = SignUpForm(request.POST)
        if signup_form.is_valid():
            user = signup_form.save()
            user.refresh_from_db()
            user.user_profile.phone_number = signup_form.cleaned_data.get(
                'phone_number')
            user.user_profile.city = signup_form.cleaned_data.get('city')
            user.save()

            current_site = get_current_site(request)
            subject = 'Activate Your MySite Account'
            message = render_to_string('acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message)
            messages.success(
                request, ('Registration Completed.Please Confirm Your Email Address'))
            return redirect('accounts:login')
        else:
            context = {
                'signup_form': signup_form,
                'title': 'Register'
            }
            return render(request, 'accounts/register.html', context)


def activate(request, uidb64, token):
    try:
        uid = force_bytes(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.user_profile.email_confirmed = True
        user.user_profile.save()
        messages.success(
            request, ('Thank You For Confirm The Email.Your Account Will Be Activated Soon'))
        return redirect('accounts:login')
    else:
        messages.success(request, ('Activation link is invalid!'))
        return redirect('accounts:login')


class LoginView(View):
    def get(self, request, *args, **kwrags):
        login_form = LoginForm()
        context = {
            'login_form': login_form,
            'title': 'Login'
        }
        return render(request, 'accounts/login.html', context)

    def post(self, request, *args, **kwrags):
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data.get('username')
            password = login_form.cleaned_data.get('password')

            user = authenticate(request, username=username,
                                password=password)
            if user is not None:
                if user.user_profile.email_confirmed and user.user_profile.active:
                    login(request, user)
                    return redirect('accounts:dashboard')
                else:
                    messages.error(request, ('Confirmed Your Email'))
                    return redirect('accounts:login')
            else:
                messages.error(
                    request, ('Invalid Credentials Or Account May Be Inactive'))
                return redirect('accounts:login')
        else:
            context = {
                'login_form': login_form,
                'title': 'Login'
            }
            return render(request, 'accounts/login.html', context)


class Dashboard(AictiveUserRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        updated_profile_form = UpdateProfileForm(request=request)
        context = {
            'title': 'Dashboard',
            'updated_profile_form': updated_profile_form
        }
        return render(request, 'accounts/dashboard.html', context)


class UpdateProfile(AictiveUserRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        phone_number = request.POST.get('phone_number')
        city = request.POST.get('city')
        profile_image = request.FILES.get('image')

        if first_name:
            request.user.first_name = first_name
        if last_name:
            request.user.last_name = last_name
        if phone_number:
            request.user.user_profile.phone_number = phone_number
        if city:
            request.user.user_profile.city = city
        if profile_image:
            request.user.user_profile.profile_pic = profile_image

        request.user.save()
        request.user.user_profile.save()

        messages.success(request, "Profile Updated Successfully")
        return redirect('accounts:dashboard')


class ChangePassword(AictiveUserRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        chanage_password_form = PasswordChangeForm(user=request.user)
        context = {
            'title': 'Chnage Password',
            'chanage_password_form': chanage_password_form
        }
        return render(request, 'accounts/change_password.html', context)

    def post(self, request, *args, **kwargs):
        chanage_password_form = PasswordChangeForm(
            data=request.POST, user=request.user)
        context = {
            'title': 'Chnage Password',
            'chanage_password_form': chanage_password_form
        }
        if chanage_password_form.is_valid():
            chanage_password_form.save()
            update_session_auth_hash(request, chanage_password_form.user)
            messages.success(request, ('You have Changed Your Password...'))
            return redirect('accounts:change_password')
        else:
            return render(request, 'accounts/change_password.html', context)


class MyProduct(generic.ListView):
    model = Product
    context_object_name = 'my_ad_list'
    paginate_by = 10
    template_name = 'accounts/my_ad_list.html'

    def get_queryset(self):
        return self.request.user.user_products.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'{self.request.user.username}-Product'
        return context


class LogoutView(AictiveUserRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        logout(request)
        messages.success(request, ('You Have Been Logged Out..'))
        return redirect('accounts:login')

merodokan2-master/templates/accounts/change_password.html
{% extends "base.html" %}

{% load static %}

{% block title %}
    {{title}}
{% endblock title %}

{% block breadcrumb %}
    <li><a href="{% url 'products:home' %}">Home</a></li>
    <li><a href="{% url 'accounts:change_password' %}">Change Password</a></li>
    <li class="active">Dashboard</li>
{% endblock breadcrumb %}


{% block content %}

        <div class="product-desc">
            {% include 'partials/_alert.html' %}
            <div class="col-md-12">
                <div class="sign-up">

                    <form action="{% url 'accounts:change_password' %}" method="POST" novalidate>
                        {% csrf_token %}
                        <div class="sign-u">
                            <div class="sign-up1">
                                <h4>{{chanage_password_form.old_password.label}}* :</h4>
                            </div>
                            <div class="sign-up2">


                                    {{chanage_password_form.old_password}}
                                    <span style="color:red">{{chanage_password_form.old_password.errors.as_text}}</span>

                            </div>
                            <div class="clearfix"> </div>
                        </div>

                        <div class="sign-u">
                            <div class="sign-up1">
                                <h4>{{chanage_password_form.new_password1.label}}* :</h4>
                            </div>
                            <div class="sign-up2">


                                    {{chanage_password_form.new_password1}}
                                    <span style="color:red">{{chanage_password_form.new_password1.errors.as_text}}</span>

                            </div>
                            <div class="clearfix"> </div>
                        </div>


                        <div class="sign-u">
                            <div class="sign-up1">
                                <h4>{{chanage_password_form.new_password2.label}}* :</h4>
                            </div>
                            <div class="sign-up2">


                                    {{chanage_password_form.new_password2}}
                                    <span style="color:red">{{chanage_password_form.new_password2.errors.as_text}}</span>

                            </div>
                            <div class="clearfix"> </div>
                        </div>







                        <div class="sub_home">
                                <div class="sub_home_left">

                                        <input type="submit" value="Update">

                                </div>

                                <div class="clearfix"> </div>
                            </div>
                    </form>
                </div>
            </div>

        </div>

{% endblock content %}

merodokan2-master/templates/accounts/dashboard.html
{% extends "base.html" %}

{% load static %}

{% block title %}
    {{title}}
{% endblock title %}

{% block breadcrumb %}
    <li><a href="{% url 'products:home' %}">Home</a></li>
    <li><a href="{% url 'accounts:change_password' %}">Change Password</a></li>
    <li><a href="{% url 'accounts:my_products' %}">My Proudcts</a></li>
    <li class="active">Dashboard</li>
{% endblock breadcrumb %}


{% block content %}

        <div class="product-desc">
            {% include 'partials/_alert.html' %}
            <div class="col-md-7">
                <div class="sign-up">
                    <form action="{% url 'accounts:update_profile' %}" method="POST" novalidate>
                        {% csrf_token %}
                        <div class="sign-u">
                            <div class="sign-up1">
                                <h4>{{updated_profile_form.first_name.label}}* :</h4>
                            </div>
                            <div class="sign-up2">


                                    {{updated_profile_form.first_name}}
                                    <span style="color:red">{{updated_profile_form.first_name.errors.as_text}}</span>

                            </div>
                            <div class="clearfix"> </div>
                        </div>

                        <div class="sign-u">
                            <div class="sign-up1">
                                <h4>{{updated_profile_form.last_name.label}}* :</h4>
                            </div>
                            <div class="sign-up2">


                                    {{updated_profile_form.last_name}}
                                    <span style="color:red">{{updated_profile_form.last_name.errors.as_text}}</span>

                            </div>
                            <div class="clearfix"> </div>
                        </div>

                        <div class="sign-u">
                            <div class="sign-up1">
                                <h4>{{updated_profile_form.phone_number.label}}* :</h4>
                            </div>
                            <div class="sign-up2">


                                    {{updated_profile_form.phone_number}}
                                    <span style="color:red">{{updated_profile_form.phone_number.errors.as_text}}</span>

                            </div>
                            <div class="clearfix"> </div>
                        </div>

                        <div class="sign-u">
                            <div class="sign-up1">
                                <h4>{{updated_profile_form.city.label}}* :</h4>
                            </div>
                            <div class="sign-up2">


                                    {{updated_profile_form.city}}
                                    <span style="color:red">{{updated_profile_form.city.errors.as_text}}</span>

                            </div>
                            <div class="clearfix"> </div>
                        </div>

                        <div class="sub_home">
                                <div class="sub_home_left">

                                        <input type="submit" value="Update">

                                </div>

                                <div class="clearfix"> </div>
                            </div>
                    </form>
                </div>
            </div>
            <div class="col-md-5">
                <img src="{{user.user_profile.profile_pic.url}}" class="img-responsive img-thumbnail img-rounded" width="236" height="236">
                <form action="{% url 'accounts:update_profile' %}" method="POST" enctype="multipart/form-data" class="form-inline">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group">
                            <input type="file" name="image" class="form-control">
                        </div>


                        <input type="submit" value="Update Image" class="btn btn-info btn-sm">

                    </div>
                </form>
            </div>
        </div>

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6">
            <div class="well well-sm">
                <div class="row">
                    <form action="{% url 'accounts:update_profile' %}" method="POST" novalidate>
                        {% csrf_token %}
                    <div class="col-sm-6 col-md-4">
                        <img src="http://placehold.it/380x500" alt="" class="img-rounded img-responsive" />
                    </div>
                    <div class="col-sm-6 col-md-8">
                        <h4>
                            {{user.first_name}} {{user.first_name}}</h4>
                        <small><cite title="San Francisco, USA">{{user.user_profile.city}}<i class="glyphicon glyphicon-map-marker">
                        </i></cite></small>
                        <p>
                            <i class="glyphicon glyphicon-envelope"></i>{{user.first_name}}
                            <br />
                            <i class="glyphicon glyphicon-globe"></i><a href="http://www.jquery2dotnet.com">{{user.user_profile.phone_number}}</a>
                            <br />
                            <i class="glyphicon glyphicon-gift"></i>{{user.username}}</p>
                        <!-- Split button -->
                        <div class="btn-group">
                            <button type="button" class="btn btn-primary">
                                Social</button>
                            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span><span class="sr-only">Social</span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Twitter</a></li>
                                <li><a href="https://plus.google.com/+Jquery2dotnet/posts">Google +</a></li>
                                <li><a href="https://www.facebook.com/jquery2dotnet">Facebook</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Github</a></li>
                            </ul>
                        </div>
                        <input href="{% url 'accounts:my_products' %}"type="submit" value="Update">
                    </div>
                    </form>
                    <a target="_blank" href="{% url 'accounts:update_profile' %}" class="btn btn-info btn-md" role="button">
                        <i class="fa fa-eye"></i>
                         Update
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

merodokan2-master/templates/accounts/login.html
{% extends "base.html" %}

{% load static %}

{% block title %}
    {{title}}
{% endblock title %}

{% block breadcrumb %}
    <li><a href="{% url 'products:home' %}">Home</a></li>
    <li class="active">Register</li>
{% endblock breadcrumb %}


{% block content %}
    <div id="page-wrapper" class="sign-in-wrapper">
                <div class="graphs">
                    <div class="sign-up">
                        {% include 'partials/_alert.html' %}
                        <h1>Login To Your Account</h1>
                        <p class="creating">Login To Your Account To Post Ad</p>
                        <h2>Personal Information</h2>
                        <form action="{% url 'accounts:login' %}" method="POST" novalidate>
                            {% csrf_token %}
                            <div class="sign-u">
                            <div class="sign-up1">
                                <h4>{{login_form.username.label}}* :</h4>
                            </div>
                            <div class="sign-up2">


                                    {{login_form.username}}
                                    <span style="color:red">{{login_form.username.errors.as_text}}</span>

                            </div>
                            <div class="clearfix"> </div>
                            </div>
                            <div class="sign-u">
                                <div class="sign-up1">
                                    <h4>{{login_form.password.label}}* :</h4>
                                </div>
                                <div class="sign-up2">

                                        {{login_form.password}}
                                        <span style="color:red">{{login_form.password.errors.as_text}}</span>

                                </div>
                                <div class="clearfix"> </div>
                            </div>

                            <div class="sub_home">
                                <div class="sub_home_left">

                                        <input type="submit" value="Login">

                                </div>
                                <div class="sub_home_right">
                                    <p>Register <a href="{% url 'accounts:register' %}">Register</a></p>
                                     <p>Register <a href="{% url 'password_reset' %}">Forget Password</a></p>
                                </div>
                                <div class="clearfix"> </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
{% endblock content %}

merodokan2-master/templates/accounts/my_ad_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {{title}}
{% endblock title %}

{% block breadcrumb %}
    <li><a href="{% url 'products:home' %}">Home</a></li>
    <li class="active">MyList</li>
{% endblock breadcrumb %}

{% block content %}

        <section class="bg-light pt-5 pb-5 shadow-sm">
            <div class="container">
              <div class="row pt-5">
                <div class="col-12">
                  <h3 class="text-uppercase border-bottom mb-4">MY PRODUCTS ON SALE</h3>
                </div>
              </div>
              <div class="row">

                {% for ad in my_ad_list %}
                <!--ADD CLASSES HERE d-flex align-items-stretch-->
                <div class="col-lg-3 mb-4 d-flex align-items-stretch">
                  <div class="card">
                    {% with ad.product_images.all|first as image %}
                    <img src="{{image.image.url}}"  class="card-img-top" alt="Card Image">
                    {% endwith %}
                    
                    <div class="card-body d-flex flex-column">

                        <h2 class="card-title">{{ad.title}}</h2>
                        <h4 class="card-text">{{ad.title}}</h4>
                        <h5 class="card-text">{{ad.price}}</h5>

                        <p>
                            <a target="_blank" href="{% url 'products:ad_detail' ad.slug  %}" class="btn btn-info btn-md" role="button">
                                <i class="fa fa-eye"></i>
                                View
                            </a>

                            <a href="{% url 'products:update_product' ad.slug %}" class="btn btn-success btn-md" role="button">
                                <i class="fa fa-edit"></i>
                                Update
                            </a>
                            <a class="delete_ad btn btn-md btn-danger"
                            data-title="Delete {{ad.title}}?"
                            href="{% url 'products:delete_ad' ad.id %}"><i class="fa fa-trash"></i> Delete</a>
                            </a>
                        </p>
                    </div>
                  </div>
                </div>
                {% endfor %}
              </div>
            </div>
          </section>  
        {% if is_paginated %}
            {% include 'partials/_pagination.html' %}
        {% endif %}
    </div>
<div class="clearfix"></div>
</div>


{% endblock content %}


{% block script %}
    <script type="text/javascript" src="{% static 'js/jquery-ui.js' %}"></script>
    <script type='text/javascript'>//<![CDATA[
    $(window).load(function(){
     $( "#slider-range" ).slider({
                range: true,
                min: 0,
                max: 9000,
                values: [ 50, 6000 ],
                slide: function( event, ui ) {  $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] );
                }
     });
    $( "#amount" ).val( "$" + $( "#slider-range" ).slider( "values", 0 ) + " - $" + $( "#slider-range" ).slider( "values", 1 ) );

    });//]]>

    </script>
{% endblock script %}