merodokan2-master/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace="accounts")),

    path('', include('products.urls', namespace="products")),

    path('pages/', include('pages.urls', namespace="pages")),



    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.FORCE_STATIC_FILE_SERVING and not settings.DEBUG:
    settings.DEBUG = True
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    settings.DEBUG = False

merodokan2-master/pages/urls.py
from django.urls import path
from . import views

app_name = "pages"

urlpatterns = [
    path('how-it-works/', views.HowItWorks.as_view(), name='how_it_works'),
    path('faq/', views.Faq.as_view(), name='faq'),
    path('feedback/', views.FeedBack.as_view(), name='feedback'),
    path('contact/', views.Contact.as_view(), name='contact'),
    path('terms/', views.Terms.as_view(), name='terms'),
    path('terms/', views.Terms.as_view(), name='terms'),
    path('privacy/', views.Privacy.as_view(), name='privacy'),
]

merodokan2-master/products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path('', views.AdList.as_view(), name='home'),
    path('detail/<slug:slug>/', views.AdDetail.as_view(), name="ad_detail"),

    path('post-ad/', views.PostAd.as_view(), name='post_ad'),
    path('delete-ad/<int:id>', views.DeleteAdd.as_view(), name='delete_ad'),

    path('user/product/<str:username>/',
         views.UserProduct.as_view(), name="user_product"),

    path('category/product/<str:slug>/',
         views.CategoryProduct.as_view(), name="category_product"),

    path('update/product/<slug:slug>/',
         views.UpdateProduct.as_view(), name="update_product"),


    path('product/search/',
         views.SearchProduct.as_view(), name="search_product"),

    path('ads/<int:year>/<int:month>/', views.ProductMonthArchiveView.as_view(month_format='%m'),
         name="archive_month_ads"),
     path('favourites/', views.product_favourite_list, name='product_favourite_list'),
     path('addfavourites/<int:id>', views.favourites, name='addfavourite'),

]

merodokan2-master/products/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify
from django.urls import reverse

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=250)
    image = models.ImageField(
        upload_to="category/%Y/%m/%d/", blank=True, null=True)

    class Meta():
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created object, so set slug
            self.slug = slugify(self.name)

        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


def generate_unique_slug(klass, field):
    origin_slug = slugify(field)
    unique_slug = origin_slug
    numb = 1
    while klass.objects.filter(slug=unique_slug).exists():
        unique_slug = '%s-%d' % (origin_slug, numb)
        numb += 1
    print(unique_slug)
    return unique_slug


class ActiveProductManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(active=True)


class Product(models.Model):
    CONDITION_CHOICES = (
        ('0', 'Used'),
        ('1', 'New'),
    )

    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='user_products')
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=250)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name='category_products')
    description = models.TextField()
    condition = models.CharField(max_length=10, choices=CONDITION_CHOICES)
    price = models.FloatField()
    brand = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    area = models.CharField(max_length=200)
    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(default=timezone.now)

    objects = models.Manager()
    active_objects = ActiveProductManager()
    favourites = models.ManyToManyField(User, related_name='favourites', blank=True)

    class Meta:
        ordering = ['-id']

    def save(self, *args, **kwargs):
        if self.slug:
            if slugify(self.title) != self.slug:
                self.slug = generate_unique_slug(Product, self.title)
        else:
            self.slug = generate_unique_slug(Product, self.title)
        super(Product, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('products:update_product', args=[str(self.slug)])

    def __str__(self):
        return self.title


class ProductImage(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name='product_images')
    image = models.ImageField(upload_to="product/%Y/%m/%d/")

    def __str__(self):
        return self.product.title

merodokan2-master/templates/ads/ad_detail.html
  
{% extends "base.html" %}

{% load static %}

{% block title %}
    {{title}}
{% endblock title %}


{% block cat_search %}
    {% include 'partials/_categories.html' %}
    {% include 'partials/_search.html' %}
{% endblock cat_search %}


{% block breadcrumb %}
    <li><a href="{% url 'products:home' %}">Home</a></li>
    <li><a href="{% url 'products:category_product' product.category.slug %}">{{product.category.name}}</a></li>
    <li>{{product.title}}</li>
{% endblock breadcrumb %}

{% block content %}

<!-- product details -->
    <div class="card">
        <div class="row">
            <aside class="col-sm-5 border-right">
    <article class="gallery-wrap"> 
    <div class="img-big-wrap">
    <div> 
        {% for image in product.product_images.all %}  
        <a href="#"><img src="{{image.image.url}}"></a></div>
            

        {% endfor %}
    </div> <!-- slider-product.// -->
    <div class="img-small-wrap">
    <div class="item-gallery"> <img src="{{image.image.url}}"> </div>
        <div class="item-gallery"> <img src="{{image.image.url}}"> </div>
    </div> <!-- slider-nav.// -->
    </article> <!-- gallery-wrap .end// -->
            </aside>
            <aside class="col-sm-7">
    <article class="card-body p-5">
        <h3 class="title mb-3">{{product.title}}</h3>

    <p class="price-detail-wrap"> 
        <span class="price h3 text-warning"> 
            <span class="currency">US $</span><span class="num">{{product.price}}</span>
        </span> 
        <span>/per kg</span> 
    </p> <!-- price-detail-wrap .// -->
    <dl class="item-property">
    <dt>Description</dt>
    <dd><p>{{product.description}} </p></dd>
    </dl>
    <dl class="param param-feature">
    <dt>Model#</dt>
    <dd>{{product.brand}}</dd>
    </dl>  <!-- item-property-hor .// -->
    <dl class="param param-feature">
    <dt>Condition</dt>
    <dd>{{product.get_condition_display}}</dd>
    </dl>  <!-- item-property-hor .// -->
    <dl class="param param-feature">
    <dt>Location</dt>
    <dd>{{product.city}},,{{product.area}}</dd>
    </dl>  <!-- item-property-hor .// -->

    <dl class="param param-feature">
        <dt>Seller</dt>
        <dd>{{product.owner.username}}</dd>
    </dl> 
    {% if is_favourite%}
          <i class="far fa-heart fa-lg"></i>
        
      {% else %}
     
          <i class="far fa-heart fa-lg"></i>
        </a>
      {% endif %}

        <a href="#" class="btn btn-lg btn-primary text-uppercase"> Buy now </a>
        <a href="tel:{{product.owner.user_profile.phone_number}}" class="btn btn-success"> <i class="fa-solid fa-phone"></i>Call Seller </a>
    </article> <!-- card-body.// -->
            </aside> <!-- col.// -->
        </div> <!-- row.// -->
    </div> <!-- card.// -->


    </div>
    <div class="row">
        <div class="col-md-12 text-center">
            <h3>Realted Products</h3>
        </div>
        <hr>
        {% for ad in related_products %}
        <div class="col-md-4">
            <div class="thumbnail">
                    {% with ad.product_images.all|first as image %}
                        <img src="{{image.image.url}}" class="img-thmbnail" />
                    {% endwith %}
                    <div class="caption">
                        <h3>{{ad.title}}</h3>
                        <p>{{ ad.description|truncatechars:20 }}</p>
                        <p>
                            <a target="_blank" href="{% url 'products:ad_detail' ad.slug  %}" class="btn btn-info btn-md">View</a>
                        </p>
                    </div>
                </div>
        </div>
        {% endfor %}

    </div>v

{% endblock content %}


{% block script %}
    <!-- FlexSlider -->
          <script defer src="{% static 'js/jquery.flexslider.js' %}"></script>
        <link rel="stylesheet" href="{% static 'css/flexslider.css' %}" type="text/css" media="screen" />

            <script>
        // Can also be used with $(document).ready()
        $(window).load(function() {
          $('.flexslider').flexslider({
            animation: "slide",
            controlNav: "thumbnails"
          });
        });
        </script>
        <!-- //FlexSlider -->
{% endblock script %}

merodokan2-master/templates/ads/ad_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {{title}}
{% endblock title %}


{% block cat_search %}
    {% include 'partials/_categories.html' %}
    {% include 'partials/_search.html' %}
{% endblock cat_search %}

{% block breadcrumb %}
    <li><a href="{% url 'products:home' %}">Home</a></li>
    <li class="active">{{title}}</li>
{% endblock breadcrumb %}

{% block content %}
<div class="ads-grid">
    <div class="side-bar col-md-3">
        <!-- <div class="search-hotel">
            <h3 class="sear-head">Name contains</h3>
            <form>
                <input type="text" value="Product name...">
                <input type="submit" value=" ">
            </form>
        </div>

        <div class="range">
            <h3 class="sear-head">Price range</h3>
            <ul class="dropdown-menu6">
                <li>

                    <div id="slider-range"></div>
                    <input type="text" id="amount" style="border: 0; color: #ffffff; font-weight: normal;" />
                </li>
            </ul>
        </div> -->
        <!--<div class="featured-ads">
            <h2 class="sear-head fer">Featured Ads</h2>
            <div class="featured-ad">
                <a href="single.html">
                    <div class="featured-ad-left">
                        <img src="images/f1.jpg" title="ad image" alt="" />
                    </div>
                    <div class="featured-ad-right">
                        <h4>Lorem Ipsum is simply dummy text of the printing industry</h4>
                        <p>$ 450</p>
                    </div>
                    <div class="clearfix"></div>
                </a>
            </div>
            <div class="featured-ad">
                <a href="single.html">
                    <div class="featured-ad-left">
                        <img src="images/f2.jpg" title="ad image" alt="" />
                    </div>
                    <div class="featured-ad-right">
                        <h4>Lorem Ipsum is simply dummy text of the printing industry</h4>
                        <p>$ 380</p>
                    </div>
                    <div class="clearfix"></div>
                </a>
            </div>
            <div class="featured-ad">
                <a href="single.html">
                    <div class="featured-ad-left">
                        <img src="images/f3.jpg" title="ad image" alt="" />
                    </div>
                    <div class="featured-ad-right">
                        <h4>Lorem Ipsum is simply dummy text of the printing industry</h4>
                        <p>$ 560</p>
                    </div>
                    <div class="clearfix"></div>
                </a>
            </div>
            <div class="clearfix"></div>
        </div> -->
        <div class="featured-ads">
            <h4 class="text-center">All Categories</h4>
            <ul class="list-group">
                {% for cat in all_categories %}
                    <li class="list-group-item">
                        <a href="{% url 'products:category_product' cat.slug %}">{{cat.name}}</a>

                        <img src="{{cat.image.url}}" width="20px">
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="featured-ads">
            <div>
                <h3 class="text-center" style="margin-bottom:5px;">Archive Ads</h3>
                <div class="panel-group" id="accordion">
                    {% regroup all_products by created_at.year as year_list %}
                    {% for year in year_list %}
                    <div class="panel panel-default">
                        <div class="panel-heading" style="padding:10px 10px;">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion" href="#{{year.grouper}}"><span class="glyphicon glyphicon-chevron-down"></span> {{ year.grouper }}</a>
                            </h4>
                        </div>
                        <div id="{{year.grouper}}" class="panel-collapse collapse">
                            <div class="panel-body">
                                {% regroup year.list by created_at.month as month_list %}
                                <ul class="list-group">
                                {% for month in month_list %}
                                    <div class="panel panel-success">
                                        <li class="list-group-item">
                                            <a href="{% url 'products:archive_month_ads' year.grouper month.grouper %}">
                                                {{ month.list.0.created_at|date:'b' }} ({{ month.list|length }})
                                            </a>
                                        </li>
                                    </div>
                                {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
               </div>

            </div>
        </div>

    </div>
            <div>
                
            </div>
        </div>

<!-- 
        <div class="container mt-5">
            <div class="row d-flex justify-content-center g-1">
                <div class="col-lg-4 mb-3 d-flex align-items-stretch">
               
                    {% for ad in ad_list %}
                        <div class="card">
                            
                            <div class="card-body">
                                {% with ad.product_images.all|first as image %}
                                <div class="product text-center"> <img src="{{image.image.url}}"  width="250">
                                {% endwith %}
                                <h5 class="card-title">{{ad.title}}</h5>
                                <p class="card-text">{{ad.description}}</p>
                                <p class="card-text">{{ad.price}}</p>
                                <p class="card-text">{{ad.created_at}}</p>
                                <p class="card-text">{{ad.city}}--{{ad.area}}</p>
                                <a href="{% url 'products:ad_detail' ad.slug  %}" class="btn btn-primary">View</a>
                                




                            </div>

                        </div>
                    {% endfor %}
                </div>   
                </div>
            </div>
        </div>


                            <div class="card-body">
                                <p>{{ad.description}}</p>
                            </div>
                            <div class="card-footer">

                            </div>
                        </div>
                    -->
                   
                        <section class="bg-light pt-5 pb-5 shadow-sm">
                            <div class="container">
                              <div class="row pt-5">
                                <div class="col-12">
                                  <h3 class="text-uppercase border-bottom mb-4">Equal height Bootstrap 5 cards example</h3>
                                </div>
                              </div>
                              <div class="row">

                                {% for ad in ad_list %}
                                <!--ADD CLASSES HERE d-flex align-items-stretch-->
                                <div class="col-lg-3 mb-3 d-flex align-items-stretch">
                                  <div class="card">
                                    {% with ad.product_images.all|first as image %}
                                    <img src="{{image.image.url}}"  class="card-img-top" alt="Card Image">
                                    {% endwith %}
                                    
                                    <div class="card-body d-flex flex-column">

                                        <h5 class="card-title">{{ad.title}}</h5>
                                        <p class="card-text">{{ad.description}}</p>
                                        <p class="card-text">{{ad.price}}</p>
                                        <p class="card-text">{{ad.created_at}}</p>
                                        <p class="card-text">{{ad.city}}--{{ad.area}}</p>
                                      <a href="{% url 'products:ad_detail' ad.slug  %}" class="btn btn-primary mt-auto align-self-start">Book now</a>
                                    </div>
                                  </div>
                                </div>
                                {% endfor %}
                              </div>
                            </div>
                          </section>  
               
            </div>
        </div>
            {% if is_paginated %}
               {% include 'partials/_pagination.html' %}
            {% endif %}

    </div>
<div class="clearfix"></div>
</div>


{% endblock content %}

{% block script %}
    <script type="text/javascript" src="{% static 'js/jquery-ui.js' %}"></script>
    <script type='text/javascript'>//<![CDATA[
    $(window).load(function(){
     $( "#slider-range" ).slider({
                range: true,
                min: 0,
                max: 9000,
                values: [ 50, 6000 ],
                slide: function( event, ui ) {  $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] );
                }
     });
    $( "#amount" ).val( "$" + $( "#slider-range" ).slider( "values", 0 ) + " - $" + $( "#slider-range" ).slider( "values", 1 ) );

    });//]]>

    </script>
{% endblock script %}

merodokan2-master/templates/ads/archive.html
{% extends "base.html" %}

{% load static %}

{% load month_tag %}

{% block title %}
    {{title}}
{% endblock title %}


{% block cat_search %}
    {% include 'partials/_categories.html' %}
    {% include 'partials/_search.html' %}
{% endblock cat_search %}


{% block breadcrumb %}
    <li><a href="{% url 'products:home' %}">Home</a></li>
    <li>{{title}}</li>
    <li>{{year}} --- {{ month|month_name }}</li>
{% endblock breadcrumb %}

{% block content %}

<div class="ads-grid">

    <div class="ads-display col-md-12">
        <div class="wrapper">
            <div class="row">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="text-center">{{year}} --- {{ month|month_name }}</h3>
                    </div>
                </div>

                    <ul class="list-group">
                        {% for ad in object_list %}
                            <div class="panel panel-success">
                                <li class="list-group-item">
                                <a target="_blank" href="{% url 'products:ad_detail' ad.slug  %}">
                               {{ ad.created_at|date:"F j, Y" }}: {{ ad.title }}
                                </a>
                            </li>

                            </div>
                        {% endfor %}
                    </ul>


                    <ul class="pager">
                        {% if previous_month %}
                            <li class="previous"><a href="{% url 'products:archive_month_ads' previous_month|date:'Y' previous_month|date:'m'   %}">Previous</a></li>
                        {% endif %}
                        {% if next_month %}
                            <li class="next">
                                <a href="{% url 'products:archive_month_ads' next_month|date:'Y'   next_month|date:'m'   %}">Next</a>
                            </li>
                        {% endif %}
                    </ul>

            </div>
        </div>
    </div>
</div>


{% endblock content %}

merodokan2-master/templates/ads/post_ad.html
{% extends "base.html" %}

{% load static %}

{% block title %}
    {{title}}
{% endblock title %}

{% block breadcrumb %}
    <li><a href="{% url 'products:home' %}">Home</a></li>
    <li class="active">Post Ad</li>
{% endblock breadcrumb %}


{% block content %}
<div class="submit-ad main-grid-border">
    {% include 'partials/_alert.html' %}
    <h2 >Post You Want to Sell</h2>
    <div class="post-ad-form">
        <form action="{% url 'products:post_ad' %}" method="POST" enctype="multipart/form-data" novalidate>
            {% csrf_token %}

            <span class="errors" style="color:red;font-weight:blod">
                {{ad_post_form.title.errors.as_text}}
            </span>
            <label>{{ad_post_form.title.label}}<span>*</span></label>
            {{ad_post_form.title}}


            <div class="clearfix"></div>

            <span class="errors" style="color:red;font-weight:blod">
                {{ad_post_form.category.errors.as_text}}
            </span>
            <label>{{ad_post_form.category.label}} <span>*</span></label>
            {{ad_post_form.category}}
            <div class="clearfix"></div>

            <span class="errors" style="color:red;font-weight:blod">
                {{ad_post_form.condition.errors.as_text}}
            </span>
            <label>{{ad_post_form.condition.label}} <span>*</span></label>
            {{ad_post_form.condition}}
            <div class="clearfix"></div>


            <span class="errors" style="color:red;font-weight:blod">
                {{ad_post_form.brand.errors.as_text}}
            </span>
            <label>{{ad_post_form.brand.label}} <span>*</span></label>
            {{ad_post_form.brand}}
            <div class="clearfix"></div>

            <span class="errors" style="color:red;font-weight:blod">
                {{ad_post_form.price.errors.as_text}}
            </span>
            <label>{{ad_post_form.price.label}} <span>*</span></label>
            {{ad_post_form.price}}
            <div class="clearfix"></div>

            <span class="errors" style="color:red;font-weight:blod">
                {{ad_post_form.description.errors.as_text}}
            </span>
           <label>{{ad_post_form.description.label}} <span>*</span></label>
            {{ad_post_form.description}}
            <div class="clearfix"></div>

            <span class="errors" style="color:red;font-weight:blod">
                {{ad_post_form.city.errors.as_text}}
            </span>
            <label>{{ad_post_form.city.label}} <span>*</span></label>
            {{ad_post_form.city}}
            <div class="clearfix"></div>

            <span class="errors" style="color:red;font-weight:blod">
                {{ad_post_form.area.errors.as_text}}
            </span>
            <label>{{ad_post_form.area.label}} <span>*</span></label>
            {{ad_post_form.area}}
            <div class="clearfix"></div>


            <div class="upload-ad-photos">
                <span class="errors" style="color:red;font-weight:blod">
                    {{ad_post_form.images.errors.as_text}}
                </span>
                <label>{{ad_post_form.images.label}} <span>*</span></label>
                <div class="photos-upload-view">
                    {{ad_post_form.images}}

                </div>
            </div>
            <div class="clearfix"></div>

            <br><br>

            <p class="post-terms">By clicking <strong>post Button</strong> you accept our <a href="terms.html" target="_blank">Terms of Use </a> and <a href="privacy.html" target="_blank">Privacy Policy</a></p>
                    <input type="submit" value="Post">
                    <div class="clearfix"></div>



        </form>

    </div>
</div>
{% endblock content %}


{% block script %}
    <script src="{% static 'js/filedrag.js' %}"></script>
{% endblock script %}

merodokan2-master/templates/ads/search_result.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {{title}}
{% endblock title %}

{% block cat_search %}
    {% include 'partials/_categories.html' %}
    {% include 'partials/_search.html' %}
{% endblock cat_search %}


{% block breadcrumb %}
    <li><a href="{% url 'products:home' %}">Home</a></li>
    <li class="active">{{title}}</li>
{% endblock breadcrumb %}

{% block content %}
<div class="ads-grid">

    <div class="ads-display col-md-12">
        {% include 'partials/_alert.html' %}
        <div class="wrapper">

            <div class="row">

                {% for ad in search_products %}
                    <div class="col-sm-6 col-md-4">
                        <div class="thumbnail">
                            {% with ad.product_images.all|first as image %}
                                <img src="{{image.image.url}}" height="80px;" title="" alt="" />
                            {% endwith %}
                            <div class="caption">
                                <h3>{{ad.title}}</h3>
                                <p>{{ ad.description|truncatechars:20 }}</p>
                                <p>
                                    <a target="_blank" href="{% url 'products:ad_detail' ad.slug  %}" class="btn btn-info btn-md" role="button">
                                        <i class="fa fa-eye"></i>
                                    </a>

                                    <a href="{% url 'products:update_product' ad.slug %}" class="btn btn-success btn-md" role="button">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <a class="delete_ad btn btn-md btn-danger"
                                    data-title="Delete {{ad.title}}?"
                                    href="{% url 'products:delete_ad' ad.id %}"><i class="fa fa-trash"></i></a>
                                    </a>
                                </p>
                            </div>
                        </div>
                    </div>
                {% endfor %}




            </div>

        </div>

    </div>
<div class="clearfix"></div>
</div>


{% endblock content %}


{% block script %}
    <script type="text/javascript" src="{% static 'js/jquery-ui.js' %}"></script>
    <script type='text/javascript'>//<![CDATA[
    $(window).load(function(){
     $( "#slider-range" ).slider({
                range: true,
                min: 0,
                max: 9000,
                values: [ 50, 6000 ],
                slide: function( event, ui ) {  $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] );
                }
     });
    $( "#amount" ).val( "$" + $( "#slider-range" ).slider( "values", 0 ) + " - $" + $( "#slider-range" ).slider( "values", 1 ) );

    });//]]>

    </script>
{% endblock script %}

merodokan2-master/templates/ads/update_ad.html
{% extends "base.html" %}

{% load static %}

{% block title %}
    {{title}}
{% endblock title %}

{% block breadcrumb %}
    <li><a href="{% url 'products:home' %}">←←Return Home</a></li>

{% endblock breadcrumb %}


{% block content %}
<div class="submit-ad main-grid-border">
    {% include 'partials/_alert.html' %}
    <h2 style="color:green;">Edit {{object.title}} Here</h2>

    <div class="post-ad-form">
        <form action="{% url 'products:update_product' object.slug %}" method="POST" novalidate>
            {% csrf_token %}

            <span class="errors" style="color:red;font-weight:blod">
                {{form.title.errors.as_text}}
            </span>
            <label>{{form.title.label}}<span>*</span></label>
            {{form.title}}
            <div class="clearfix"></div>

            <span class="errors" style="color:red;font-weight:blod">
                {{form.price.errors.as_text}}
            </span>
            <label>{{form.price.label}}<span>*</span></label>
            {{form.price}}
            <div class="clearfix"></div>

            <span class="errors" style="color:red;font-weight:blod">
                {{form.description.errors.as_text}}
            </span>
            <label>{{form.description.label}} <span>*</span></label>
            {{form.description}}
            <div class="clearfix"></div>

            <span class="errors" style="color:red;font-weight:blod">
                {{form.brand.errors.as_text}}
            </span>
            <label>{{form.brand.label}}<span>*</span></label>
            {{form.brand}}
            <div class="clearfix"></div>

            <span class="errors" style="color:red;font-weight:blod">
                {{form.city.errors.as_text}}
            </span>
            <label>{{form.city.label}}<span>*</span></label>
            {{form.city}}
            <div class="clearfix"></div>

            <span class="errors" style="color:red;font-weight:blod">
                {{form.area.errors.as_text}}
            </span>
            <label>{{form.area.label}}<span>*</span></label>
            {{form.area}}
            <div class="clearfix"></div>

             <br><br>

            <p class="post-terms">By clicking <strong>update Button</strong> you accept our <a href="terms.html" target="_blank">Terms of Use </a> and <a href="privacy.html" target="_blank">Privacy Policy</a></p>
                    <input type="submit" value="Update">
                    <div class="clearfix"></div>
        </form>
    </div>

{% endblock content %}