merodokan2-master/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace="accounts")),

    path('', include('products.urls', namespace="products")),

    path('pages/', include('pages.urls', namespace="pages")),



    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.FORCE_STATIC_FILE_SERVING and not settings.DEBUG:
    settings.DEBUG = True
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    settings.DEBUG = False

merodokan2-master/pages/urls.py
from django.urls import path
from . import views

app_name = "pages"

urlpatterns = [
    path('how-it-works/', views.HowItWorks.as_view(), name='how_it_works'),
    path('faq/', views.Faq.as_view(), name='faq'),
    path('feedback/', views.FeedBack.as_view(), name='feedback'),
    path('contact/', views.Contact.as_view(), name='contact'),
    path('terms/', views.Terms.as_view(), name='terms'),
    path('terms/', views.Terms.as_view(), name='terms'),
    path('privacy/', views.Privacy.as_view(), name='privacy'),
]

merodokan2-master/products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path('', views.AdList.as_view(), name='home'),
    path('detail/<slug:slug>/', views.AdDetail.as_view(), name="ad_detail"),

    path('post-ad/', views.PostAd.as_view(), name='post_ad'),
    path('delete-ad/<int:id>', views.DeleteAdd.as_view(), name='delete_ad'),

    path('user/product/<str:username>/',
         views.UserProduct.as_view(), name="user_product"),

    path('category/product/<str:slug>/',
         views.CategoryProduct.as_view(), name="category_product"),

    path('update/product/<slug:slug>/',
         views.UpdateProduct.as_view(), name="update_product"),


    path('product/search/',
         views.SearchProduct.as_view(), name="search_product"),

    path('ads/<int:year>/<int:month>/', views.ProductMonthArchiveView.as_view(month_format='%m'),
         name="archive_month_ads"),
     path('favourites/', views.product_favourite_list, name='product_favourite_list'),
     path('addfavourites/<int:id>', views.favourites, name='addfavourite'),

]

merodokan2-master/templates/pages/contact.html
{% extends "base.html" %}

{% load static %}

{% load static %}

{% block title %}
    {{title}}
{% endblock title %}


{% block breadcrumb %}
    <li><a href="{% url 'products:home' %}">Home</a></li>
    <li>{{title}}</li>
{% endblock breadcrumb %}


{% block content %}
    <div class="contact main-grid-border">
        <div class="container">
            {% include 'partials/_alert.html' %}
            <h2 class="head text-center">Contact Us</h2>
            <section id="hire">
                <form id="filldetails" method="POST" action="{% url 'pages:contact' %}" novalidate>
                    {% csrf_token %}
                      <div class="field name-box">

                            {{contact_form.name}}
                            {% if contact_form.name.errors %}
                                <label for="name">{{contact_form.name.errors.as_text}}</label>
                            {% else %}
                                <label for="name">{{contact_form.name.label}}</label>
                            {% endif %}


                            <span class="ss-icon">check</span>
                      </div>

                      <div class="field email-box">
                            {{contact_form.email}}
                            {% if contact_form.email.errors %}
                                <label for="email">{{contact_form.email.errors.as_text}}</label>
                            {% else %}
                                <label for="email">{{contact_form.email.label}}</label>
                            {% endif %}

                      </div>

                      <div class="field ad-ID">
                            {{contact_form.ad_url}}
                            {% if contact_form.ad_url.errors %}
                                <label for="ad_url">{{contact_form.ad_url.errors.as_text}}</label>
                            {% else %}
                                <label for="ad_url">{{contact_form.ad_url.label}}</label>
                            {% endif %}

                      </div>

                      <div class="field phonenum-box">
                            {{contact_form.phone_number}}
                           {% if contact_form.phone_number.errors %}
                                <label for="phone_number">{{contact_form.phone_number.errors.as_text}}</label>
                            {% else %}
                                <label for="phone_number">{{contact_form.phone_number.label}}</label>
                            {% endif %}

                      </div>

                      <div class="field msg-box">
                             {{contact_form.message}}
                            {% if contact_form.message.errors %}
                                <label for="message">{{contact_form.message.errors.as_text}}</label>
                            {% else %}
                                <label for="message">{{contact_form.message.label}}</label>
                            {% endif %}

                      </div>

                    <div class="clear"></div>

                <input class="button" type="submit" value="Send" />
            </form>
</section>
</div>

</div>

{% endblock content %}


{% block script %}
    <!-- JavaScript Includes -->
        <script src="{% static 'js/jquery.knob.js' %}"></script>

        <!-- Our main JS file -->
        <script src="{% static 'js/script.js' %}"></script>
        <script>
                  $('textarea').blur(function () {
                $('#hire textarea').each(function () {
                    $this = $(this);
                    if (this.value != '') {
                        $this.addClass('focused');
                        $('textarea + label + span').css({ 'opacity': 1 });
                    } else {
                        $this.removeClass('focused');
                        $('textarea + label + span').css({ 'opacity': 0 });
                    }
                });
            });
            $('#hire .field:first-child input').blur(function () {
                $('#hire .field:first-child input').each(function () {
                    $this = $(this);
                    if (this.value != '') {
                        $this.addClass('focused');
                        $('.field:first-child input + label + span').css({ 'opacity': 1 });
                    } else {
                        $this.removeClass('focused');
                        $('.field:first-child input + label + span').css({ 'opacity': 0 });
                    }
                });
            });
            $('#hire .field:nth-child(2) input').blur(function () {
                $('#hire .field:nth-child(2) input').each(function () {
                    $this = $(this);
                    if (this.value != '') {
                        $this.addClass('focused');
                        $('.field:nth-child(2) input + label + span').css({ 'opacity': 1 });
                    } else {
                        $this.removeClass('focused');
                        $('.field:nth-child(2) input + label + span').css({ 'opacity': 0 });
                    }
                });
            });
            $('#hire .field:nth-child(3) input').blur(function () {
                $('#hire .field:nth-child(3) input').each(function () {
                    $this = $(this);
                    if (this.value != '') {
                        $this.addClass('focused');
                        $('.field:nth-child(3) input + label + span').css({ 'opacity': 1 });
                    } else {
                        $this.removeClass('focused');
                        $('.field:nth-child(3) input + label + span').css({ 'opacity': 0 });
                    }
                });
            });
            $('#hire .field:nth-child(4) input').blur(function () {
                $('#hire .field:nth-child(4) input').each(function () {
                    $this = $(this);
                    if (this.value != '') {
                        $this.addClass('focused');
                        $('.field:nth-child(4) input + label + span').css({ 'opacity': 1 });
                    } else {
                        $this.removeClass('focused');
                        $('.field:nth-child(4) input + label + span').css({ 'opacity': 0 });
                    }
                });
            });
          //@ sourceURL=pen.js
        </script>
        <script>
      if (document.location.search.match(/type=embed/gi)) {
        window.parent.postMessage("resize", "*");
      }
    </script>
{% endblock script %}

merodokan2-master/templates/pages/faq.html
{% extends "base.html" %}

{% load static %}

{% load static %}

{% block title %}
    {{title}}
{% endblock title %}


{% block breadcrumb %}
    <li><a href="{% url 'products:home' %}">Home</a></li>
    <li>{{title}}</li>
{% endblock breadcrumb %}


{% block content %}
        <div class="faq main-grid-border">
        <div class="container">
            <h2 class="head">Faqs</h2>
            <dl class="faq-list">
                <dt class="faq-list_h">
                <h4 class="marker">Q?</h4>
                <h5 class="marker_head">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium?</h5>
                </dt>
                <dd>
                <h4 class="marker1">A.</h4>
                <p class="m_13">Vestibulum ante ipsum primis in faucibus orci luctus et trices posuere cubilia Suspendisse sollicitudin velit sed leo. Ut pharetra augue nec augue. Nam elit magnandrerit sit amet tincidunt ac viverra sed nulla. Donec porta diam eu massa. Quisque diam lorem interdum vapibus ac scelerisque vitae pede. Donec eget tellus non erat lacinia fermentum. Donec in velit vel ipsum auctorulvinar. Proin ullamcorper urna et tibulum iaculis lacinia est. Proin dictum elementum velit. Fusce euismod consequat ante. Lorem ipsum dolor sit amet consectetuer adipiscing elit. Pellentese sed dolor. Aliquam congue fermentum nisl. Mauris accumsan nullael diam. Sed in lacus ut enim adipiscing aliquet.</p>
                </dd>
                <dt class="faq-list_h">
                <h4 class="marker">Q?</h4>
                <h5 class="marker_head">But I must explain to you how all this mistaken idea of denouncing?</h5>
                </dt>
                <dd>
                <h4 class="marker">A.</h4>
                <p class="m_13">Aenean auctor wisi et urna. Aliquarat volutpat. Duis ac turpis. Integer rutrum ante eu lacusVestibulum libero nisl porta vel scelerisque eget malesuada at neque. Vivamus eget nibh. Etiamcursus leo vel metus. Nulla facilisi. Aenean nec eros.</p>
                </dd>
                <dt class="faq-list_h">
                <h4 class="marker">Q?</h4>
                <h5 class="marker_head">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis ?</h5>
                </dt>
                <dd>
                <h4 class="marker">A.</h4>
                <p class="m_13">Nulla dui. Fusce feugiat malesuada odio. Morbi nunc odio gravida atcursus nec luctus a lorem. Maecenas tristique orci ac sem. Duis ultricies pharetra magna. Donec accumsan malesuada orci. Donec sit amet eros. Lorem ipsum dolor sit amet consectetuer adipiscing elit. Mauris fermentum dictum magna. Sed laoreet aliquam leo. Ut tellus dolor dapibus eget elementum vel cursus eleifend elit.</p>
                </dd>
                <dt class="faq-list_h">
                <h4 class="marker">Q?</h4>
                <h5 class="marker_head">On the other hand, we denounce with righteous indignation and dislike ?</h5>
                </dt>
                <dd>
                <h4 class="marker">A.</h4>
                <p class="m_13">Donec eget tellus non erat lacinia fermentum. Donec in velit vel ipsum auctorulvinar. Proin ullamcorper urna et tibulum iaculis lacinia est. Proin dictum elementum velit. Fusce euismod consequat ante. Lorem ipsum dolor sit amet consectetuer adipiscing elit. Pellentese sed dolor. Aliquam congue fermentum nisl. Mauris accumsan nullael diam. Sed in lacus ut enim adipiscing aliquet. Donec eget tellus non erat lacinia fermentum. Donec in velit vel ipsum auctorulvinar. Proin ullamcorper urna et tibulum iaculis lacinia est.</p>
                </dd>
                <dt class="faq-list_h">
                <h4 class="marker">Q?</h4>
                <h5 class="marker_head">Lorem ipsum dolor sit amet, consectetur adipiscing elit,?</h5>
                </dt>
                <dd>
                <h4 class="marker">A.</h4>
                <p class="m_13">Vestibulum ante ipsum primis in faucibus orci luctus et trices posuere cubilia Suspendisse sollicitudin velit sed leo. Ut pharetra augue nec augue. Nam elit magnandrerit sit amet tincidunt ac viverra sed nulla. Donec porta diam eu massa. Quisque diam lorem interdum vapibus ac scelerisque vitae pede. Donec eget tellus non erat lacinia fermentum. Donec in velit vel ipsum auctorulvinar. Proin ullamcorper urna et tibulum iaculis lacinia est. Proin dictum elementum velit. Fusce euismod consequat ante. Lorem ipsum dolor sit amet consectetuer adipiscing elit. Pellentese sed dolor. Aliquam congue fermentum nisl. Mauris accumsan nullael diam. Sed in lacus ut enim adipiscing aliquet.</p>
                </dd>
                <dt class="faq-list_h">
                <h4 class="marker">Q?</h4>
                <h5 class="marker_head">It is a long established fact that a reader will be distracted?</h5>
                </dt>
                <dd>
                <h4 class="marker">A.</h4>
                <p class="m_13">Aenean auctor wisi et urna. Aliquarat volutpat. Duis ac turpis. Integer rutrum ante eu lacusVestibulum libero nisl porta vel scelerisque eget malesuada at neque. Vivamus eget nibh. Etiamcursus leo vel metus. Nulla facilisi. Aenean nec eros.</p>
                </dd>
                <dt class="faq-list_h">
                <h4 class="marker">Q?</h4>
                <h5 class="marker_head">If you are going to use a passage of Lorem Ipsum?</h5>
                </dt>
                <dd>
                <h4 class="marker">A.</h4>
                <p class="m_13 last_2">Nulla dui. Fusce feugiat malesuada odio. Morbi nunc odio gravida atcursus nec luctus a lorem. Maecenas tristique orci ac sem. Duis ultricies pharetra magna. Donec accumsan malesuada orci. Donec sit amet eros. Lorem ipsum dolor sit amet consectetuer adipiscing elit. Mauris fermentum dictum magna. Sed laoreet aliquam leo. Ut tellus dolor dapibus eget elementum vel cursus eleifend elit.</p>
                </dd>
          </dl>

        </div>
    </div>
{% endblock content %}

merodokan2-master/templates/pages/feedback.html
{% extends "base.html" %}

{% load static %}

{% load static %}

{% block title %}
    {{title}}
{% endblock title %}


{% block breadcrumb %}
    <li><a href="{% url 'products:home' %}">Home</a></li>
    <li>{{title}}</li>
{% endblock breadcrumb %}


{% block content %}
    <div class="feedback main-grid-border">
        <div class="container">
            <h2 class="head">Feedback</h2>
            <div class="feed-back">
                <h3>Tell us what you think of us</h3>
                <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
                <div class="feed-back-form">
                    {% include 'partials/_alert.html' %}
                    <form method="POST" action="{% url 'pages:feedback' %}" novalidate>
                    {% csrf_token %}
                    <span>User Details</span><br>
                        <span style="color:red">{{feed_back_form.first_name.errors.as_text}}</span>
                        {{feed_back_form.first_name}}



                        <span style="color:red">{{feed_back_form.last_name.errors.as_text}}</span>
                        {{feed_back_form.last_name}}


                        <span style="color:red">{{feed_back_form.email.errors.as_text}}</span>
                        {{feed_back_form.email}}


                        <span style="color:red">{{feed_back_form.phone_number.errors.as_text}}</span>
                        {{feed_back_form.phone_number}}

                        <span>Is there anything you would like to tell us?</span><br>
                        <span style="color:red">{{feed_back_form.message.errors.as_text}}</span>
                        {{feed_back_form.message}}


                        <input type="submit" value="submit">
                        </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

merodokan2-master/templates/pages/how_it_works.html
{% extends "base.html" %}

{% load static %}

{% load static %}

{% block title %}
    {{title}}
{% endblock title %}


{% block breadcrumb %}
    <li><a href="{% url 'products:home' %}">Home</a></li>
    <li>{{title}}</li>
{% endblock breadcrumb %}


{% block content %}
    <div class="work-section">
            <div class="container">
                <h2 class="head">How It Works</h2>
                    <div class="work-section-head text-center">
                        <p>Fast, easy and free to post an ad and you will find, what you are looking for.</p>
                    </div>
                    <div class="work-section-grids text-center">
                        <div class="col-md-3 work-section-grid">
                            <i class="fa fa-pencil-square-o"></i>
                            <h4>Post an Ad</h4>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been</p>
                            <span class="arrow1"><img src="{% static 'images/arrow1.png' %}" alt="" /></span>
                        </div>
                        <div class="col-md-3 work-section-grid">
                            <i class="fa fa-eye"></i>
                            <h4>Find an item</h4>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been</p>
                            <span class="arrow2"><img src="{% static 'images/arrow2.png' %}" alt="" /></span>
                        </div>
                        <div class="col-md-3 work-section-grid">
                            <i class="fa fa-phone"></i>
                            <h4>contact the seller</h4>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been</p>
                            <span class="arrow1"><img src="{% static 'images/arrow1.png' %}" alt="" /></span>
                        </div>
                        <div class="col-md-3 work-section-grid">
                            <i class="fa fa-money"></i>
                            <h4>make transactions</h4>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been</p>
                        </div>
                        <div class="clearfix"></div>
                        <a class="work" href="{% url 'products:home' %}">Get start Now</a>
                    </div>
                </div>
        </div>
{% endblock content %}

merodokan2-master/templates/pages/privacy.html
{% extends "base.html" %}

{% load static %}

{% load static %}

{% block title %}
    {{title}}
{% endblock title %}


{% block breadcrumb %}
    <li><a href="{% url 'products:home' %}">Home</a></li>
    <li>{{title}}</li>
{% endblock breadcrumb %}


{% block content %}
    <div class="privacy main-grid-border">
        <div class="container">
            <h2 class="head">Privacy Policy</h2>
                <p>On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur.</p>
                <h4>Security:</h4>
                <p class="privacy-para">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum</p>
                <ol class="privacy-start">
                    <li><a href="javascript:void(0)">But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids .</a></li>
                    <li><a href="javascript:void(0)">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed .</a></li>
                    <li><a href="javascript:void(0)">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse.</a></li>
                    <li><a href="javascript:void(0)">But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids .</a></li>
                    <li><a href="javascript:void(0)">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed .</a></li>
                    <li><a href="javascript:void(0)">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse.</a></li>
                </ol>
                <h4 class="use-privay">Tips for safe transaction:</h4>
                <ul class="privacy-start">
                    <li><a href="javascript:void(0)">Contrary to popular belief, Lorem Ipsum is not simply random text.</a></li>
                    <li><a href="javascript:void(0)">There are many variations of passages of Lorem Ipsum available.</a></li>
                    <li><a href="javascript:void(0)">It is a long established fact that a reader will be distracted.</a></li>
                    <li><a href="javascript:void(0)">Lorem Ipsum is simply dummy text of the printing.</a></li>
                    <li><a href="javascript:void(0)">Sed ut perspiciatis unde omnis iste natus error sit voluptatem.</a></li>
                    <li><a href="javascript:void(0)">Contrary to popular belief, Lorem Ipsum is not simply random text.</a></li>
                    <li><a href="javascript:void(0)">There are many variations of passages of Lorem Ipsum available.</a></li>
                    <li><a href="javascript:void(0)">It is a long established fact that a reader will be distracted.</a></li>
                    <li><a href="javascript:void(0)">Lorem Ipsum is simply dummy text of the printing.</a></li>
                    <li><a href="javascript:void(0)">Sed ut perspiciatis unde omnis iste natus error sit voluptatem.</a></li>
                    <li><a href="javascript:void(0)">Contrary to popular belief, Lorem Ipsum is not simply random text.</a></li>
                    <li><a href="javascript:void(0)">There are many variations of passages of Lorem Ipsum available.</a></li>
                    <li><a href="javascript:void(0)">It is a long established fact that a reader will be distracted.</a></li>
                    <li><a href="javascript:void(0)">Lorem Ipsum is simply dummy text of the printing.</a></li>
                    <li><a href="javascript:void(0)">Sed ut perspiciatis unde omnis iste natus error sit voluptatem.</a></li>
                </ul>
        </div>
    </div>
{% endblock content %}

merodokan2-master/templates/pages/terms.html
{% extends "base.html" %}

{% load static %}

{% load static %}

{% block title %}
    {{title}}
{% endblock title %}


{% block breadcrumb %}
    <li><a href="{% url 'products:home' %}">Home</a></li>
    <li>{{title}}</li>
{% endblock breadcrumb %}


{% block content %}
     <div class="terms main-grid-border">
        <div class="container">
            <h2 class="head">Terms of Use</h2>
                <div class="panel-group" id="accordion">
                <!-- First Panel -->
                {% for term in all_terms %}


                    <div class="panel panel-default">
                        <div class="panel-heading">
                             <h4 class="panel-title" data-toggle="collapse" data-target="#{{term.id}}">
                                 <span>{{forloop.counter}}.</span> {{term.name}}
                             </h4>
                        </div>
                        <div id="{{term.id}}" class="panel-collapse collapse">
                            <div class="panel-body">
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                                <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage.</p>
                            </div>
                        </div>
                    </div>


                {% endfor %}

                </div>
        </div>
    </div>
{% endblock content %}